In [1]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.tree import export_text
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split

X = np.array([
    [20, 4], [22, 5], [25, 6],
    [30, 10], [32, 12], [35, 14],
    [40, 18], [45, 20], [48, 22],
    [52, 25], [55, 28], [60, 30],
    [62, 32], [65, 35], [70, 40],
    [30, 10], [45, 20], [60, 30],
    [18, 3], [21, 4], [24, 5],
    [28, 9], [33, 11], [36, 15],
    [25, 6], [55, 28], [40, 18],
    [68, 38], [72, 42], [66, 36]
])

y = np.array([
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "dog",
    "horse", "horse", "horse",
    "horse", "horse", "horse",
    "cat", "horse", "dog",
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "horse",
    "horse", "horse", "horse"
])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  

clf = DecisionTreeClassifier(criterion='gini', random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

tree_rules = export_text(clf, feature_names=["X1", "X2"], show_weights=True)
print(tree_rules)

Accuracy: 0.5
Confusion Matrix:
 [[0 1 0]
 [0 2 1]
 [0 1 1]]
|--- X1 <= 26.50
|   |--- X2 <= 5.50
|   |   |--- weights: [5.00, 0.00, 0.00] class: cat
|   |--- X2 >  5.50
|   |   |--- weights: [1.00, 1.00, 0.00] class: cat
|--- X1 >  26.50
|   |--- X2 <= 29.00
|   |   |--- X1 <= 37.50
|   |   |   |--- weights: [0.00, 5.00, 0.00] class: dog
|   |   |--- X1 >  37.50
|   |   |   |--- X2 <= 19.00
|   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |   |--- X2 >  19.00
|   |   |   |   |--- X1 <= 50.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |   |   |--- X1 >  50.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |--- X2 >  29.00
|   |   |--- weights: [0.00, 0.00, 6.00] class: horse



In [3]:
from sklearn.model_selection import train_test_split

X = np.array([
    [20, 4], [22, 5], [25, 6],
    [30, 10], [32, 12], [35, 14],
    [40, 18], [45, 20], [48, 22],
    [52, 25], [55, 28], [60, 30],
    [62, 32], [65, 35], [70, 40],
    [30, 10], [45, 20], [60, 30],
    [18, 3], [21, 4], [24, 5],
    [28, 9], [33, 11], [36, 15],
    [25, 6], [55, 28], [40, 18],
    [68, 38], [72, 42], [66, 36]
])

y = np.array([
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "dog",
    "horse", "horse", "horse",
    "horse", "horse", "horse",
    "cat", "horse", "dog",
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "horse",
    "horse", "horse", "horse"
])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  

clf = DecisionTreeClassifier(criterion='gini', random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

tree_rules = export_text(clf, feature_names=["X1", "X2"], show_weights=True)
print(tree_rules)

Accuracy: 0.5555555555555556
Confusion Matrix:
 [[0 1 0]
 [1 2 1]
 [0 1 3]]
|--- X1 <= 26.50
|   |--- weights: [6.00, 0.00, 0.00] class: cat
|--- X1 >  26.50
|   |--- X2 <= 16.00
|   |   |--- weights: [0.00, 5.00, 0.00] class: dog
|   |--- X2 >  16.00
|   |   |--- X2 <= 29.00
|   |   |   |--- X1 <= 42.50
|   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |   |--- X1 >  42.50
|   |   |   |   |--- X2 <= 24.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |   |   |--- X2 >  24.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |--- X2 >  29.00
|   |   |   |--- weights: [0.00, 0.00, 4.00] class: horse



In [5]:
from sklearn.model_selection import train_test_split

X = np.array([
    [20, 4], [22, 5], [25, 6],
    [30, 10], [32, 12], [35, 14],
    [40, 18], [45, 20], [48, 22],
    [52, 25], [55, 28], [60, 30],
    [62, 32], [65, 35], [70, 40],
    [30, 10], [45, 20], [60, 30],
    [18, 3], [21, 4], [24, 5],
    [28, 9], [33, 11], [36, 15],
    [25, 6], [55, 28], [40, 18],
    [68, 38], [72, 42], [66, 36]
])

y = np.array([
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "dog",
    "horse", "horse", "horse",
    "horse", "horse", "horse",
    "cat", "horse", "dog",
    "cat", "cat", "cat",
    "dog", "dog", "dog",
    "dog", "dog", "horse",
    "horse", "horse", "horse"
])


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)  

clf = DecisionTreeClassifier(criterion='gini', random_state=42)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

tree_rules = export_text(clf, feature_names=["X1", "X2"], show_weights=True)
print(tree_rules)

#Compare how the different split ratios affect the results

 Different split ratios changed the results: smaller training sets gave lower accuracy, while larger training sets improved performance. 
 In short - more training data = better learning.

#Predict the animal type with features [34, 17] Use the trained model to predict its class

clf.predict([[34, 17]])

Accuracy: 0.5833333333333334
Confusion Matrix:
 [[1 1 0]
 [1 3 1]
 [0 2 3]]
|--- X1 <= 26.50
|   |--- weights: [5.00, 0.00, 0.00] class: cat
|--- X1 >  26.50
|   |--- X2 <= 29.00
|   |   |--- X2 <= 16.00
|   |   |   |--- weights: [0.00, 4.00, 0.00] class: dog
|   |   |--- X2 >  16.00
|   |   |   |--- X1 <= 42.50
|   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |   |   |--- X1 >  42.50
|   |   |   |   |--- X2 <= 24.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 0.00] class: dog
|   |   |   |   |--- X2 >  24.00
|   |   |   |   |   |--- weights: [0.00, 1.00, 1.00] class: dog
|   |--- X2 >  29.00
|   |   |--- weights: [0.00, 0.00, 4.00] class: horse



array(['dog'], dtype='<U5')